=== 62mkv/mlib/src/main/java/server/com/sam/webservices/config/resources/service-config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT service-config (service+)>
<!ELEMENT service (operation*)>
<!ATTLIST service 
    name CDATA #REQUIRED
    class CDATA #IMPLIED
    package CDATA #IMPLIED
    generate (true|false) "true" >

<!ELEMENT operation (input?, command, output?)>
<!ATTLIST operation
    name CDATA #REQUIRED>

<!ELEMENT input (argument*)>

<!ELEMENT argument EMPTY>
<!ATTLIST argument
    name CDATA #REQUIRED
    type (string|integer|double|boolean) #REQUIRED
    column CDATA #IMPLIED
    nullable (true|false) "false" >

<!ELEMENT command (#PCDATA)>

<!ELEMENT output (field*)>
<!ATTLIST output
	class CDATA #IMPLIED
	multirow CDATA #IMPLIED>

<!ELEMENT field EMPTY>
<!ATTLIST field
    name CDATA #REQUIRED
    type (string|integer|double|boolean) #REQUIRED
    column CDATA #IMPLIED
    nullable (true|false) "true" >

=== 62mkv/mlib/test/src/java/com/redprairie/webservices/config/test/service_config12.xml
<?xml version="1.0"?>
<!DOCTYPE service-config SYSTEM "service-config.dtd">
<service-config>
    <service name="myservice" class="MyService" package="com.redprairie.services.core">
        <operation name="operation1">
            <input>                
            </input>
            <command><![CDATA[some MOCA command | some other moca command where x=@something]]></command>
            <output multirow="true" class="MyResult">
                <field name="field1" type="string" nullable="true"/>
                <field name="field2" type="integer" nullable="true"/>
                <field name="field3" type="boolean" nullable="false"/>
                <field name="field4" type="double" nullable="true"/>
            </output>
        </operation>
		<operation name="operation2">
            <input>
                <argument name="argName2" type="string"/>
                <argument name="something2" type="integer"/>
                <argument name="somethingElse2" type="double"/>
            </input>
            <command><![CDATA[some MOCA command2 | some other moca command where x=@something]]></command>
            <output multirow="true" class="MyResult2">
                <field name="field12" type="string" nullable="true"/>
                <field name="field22" type="integer" nullable="true"/>
                <field name="field32" type="boolean" nullable="false"/>
                <field name="field42" type="double" nullable="true"/>
            </output>
        </operation>
    </service>
      <service name="myservice1" class="MyService1" package="com.redprairie.services.core">
        <operation name="operation3">
            <input>
                <argument name="argName3" type="string"/>
                <argument name="something3" type="integer"/>
                <argument name="somethingElse3" type="double"/>
            </input>
            <command><![CDATA[some MOCA command3 | some other moca command where x=@something]]></command>
            <output multirow="false" class="MyResult3">
                <field name="field13" type="string" nullable="true"/>
                <field name="field23" type="integer" nullable="true"/>
                <field name="field33" type="boolean" nullable="false"/>
                <field name="field43" type="double" nullable="true"/>
            </output>
        </operation>
		<operation name="operation4">
            <input>
                <argument name="argName4" type="string"/>
                <argument name="something4" type="integer"/>
                <argument name="somethingElse4" type="double"/>
            </input>
            <command><![CDATA[some MOCA command4 | some other moca command where x=@something]]></command>
            <output multirow="true" class="MyResult4">
                <field name="field14" type="string" nullable="true"/>
                <field name="field24" type="integer" nullable="true"/>
                <field name="field34" type="boolean" nullable="false"/>
                <field name="field44" type="double" nullable="true"/>
            </output>
        </operation>
    </service>    
</service-config>

=== 62mkv/mlib/test/src/java/com/redprairie/webservices/config/test/command.svc.xml
<?xml version="1.0"?>
<!DOCTYPE service-config SYSTEM "service-config.dtd">
<service-config>
    <service name="commandService" class="CommandService" package="com.redprairie.services.core">
        <operation name="listAllCommands">
            <command><![CDATA[list active commands]]></command>
            <output multirow="true" class="ActiveCommand">
                <field name="verb" type="string" nullable="false"/>
                <field name="noun" type="string" nullable="false"/>
                <field name="command" type="string" nullable="false"/>
                <field name="cmdtyp" type="string" nullable="false"/>
                <field name="cmplvl" type="string" nullable="false"/>
                <field name="cmplvlseq" type="integer" nullable="false"/>
                <field name="functn" type="string" nullable="true"/>
                <field name="syntax" type="string" nullable="true"/>
                <field name="insflg" type="boolean" nullable="false"/>
            </output>
        </operation>
    </service>
</service-config>
